[env]
SYSTEM_DEPS_BUILD_INTERNAL="always"
[build]
rustflags=["-C", "link-args=-Wl,-lc"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-args=-Wl,-lc","-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = ["-C", "link-args=-Wl,-lc","-C", "link-arg=-fuse-ld=/usr/bin/mold"]
