name: e2e test

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "develop","master","e2e-wip" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "develop","master","e2e-wip" ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test-cherrypick
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: setup config
        run: |
          mkdir ${{github.workspace}}/.config
          cp -a e2e-test/config/* ${{github.workspace}}/.config/
      - name: Run cherrypick
        run: |
          docker run -d -p 3000:3000 --name cherrypick -v ${{github.workspace}}/.config:/cherrypick/.config:ro ghcr.io/yojo-art/cherrypick:develop
      - name: Build App
        run: cargo build --release
      - name: Run App
        run: cd ${{github.workspace}} && ./target/release/yojo-art-rs &
      - name: Build Test
        run: |
          cd ${{github.workspace}}/e2e-test
          cargo test build
      - name: Sleep
        run: |
          sleep 10
      - name: Check App Running
        run: |
          test -n $(ls -l /proc/*/exe 2>&1 | awk {'print $11'} | grep yojo-art-rs)
      - name: Run Test
        run: |
          cd ${{github.workspace}}/e2e-test
          cargo test
